- name: "Migrate image tag {{ item.destination_image }}"
  shell: "skopeo copy --src-creds {{ source_registry.username }}:{{ source_registry.password }} --dest-creds {{ destination_registry.username }}:{{ destination_registry.password }} --src-tls-verify=false --dest-tls-verify=false docker://{{ source_registry.url }}/{{ item.source_image }} docker://{{ destination_registry.url }}/{{ item.destination_image }}"
  register: skopeo_output
  ignore_errors: true

- name: "Collect failed image tags"
  vars:
    failed_tag:
      - "{{ item | combine({'stderr': skopeo_output.stderr, 'rc': skopeo_output.rc}) }}"
  set_fact:
    failed_tags: "{{ failed_tags + failed_tag }}"
  when: skopeo_output.rc != 0